AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'
