export default [
  'Argentina',
  'Australia',
  'Belgium',
  'Brazil',
  'China',
  'Czech Republic',
  'Denmark',
  'Europe',
  'Finland',
  'Hungary',
  'India',
  'Indonesia',
  'Japan',
  'Korea',
  'Mongolia',
  'Netherlands',
  'North America',
  'Oceania',
  'Other',
  'Philippines',
  'Poland',
  'Singapore',
  'South Africa',
  'South America',
  'Sweden',
  'Thailand',
  'Turkey',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Vietnam',
];
