/* tslint:disable */
/* eslint-disable */
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

/**
 * Autogenerated input type of UpdateTournamentMutation
 */
export interface UpdateTournamentMutationInput {
  clientMutationId?: string | null;
  endAt: any;
  id: string;
  location?: string | null;
  name: string;
  startAt: any;
}

//==============================================================
// END Enums and Input Objects
//==============================================================
