/* tslint:disable */
/* eslint-disable */
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

/**
 * Autogenerated input type of CreateMatchMutation
 */
export interface CreateMatchMutationInput {
  clientMutationId?: string | null;
  endAt?: any | null;
  lowerRosterId?: string | null;
  startAt: any;
  tournamentId: string;
  upperRosterId?: string | null;
  winnerId?: string | null;
}

/**
 * Autogenerated input type of CreateTournamentMutation
 */
export interface CreateTournamentMutationInput {
  clientMutationId?: string | null;
  endAt?: any | null;
  location?: string | null;
  name: string;
  startAt: any;
}

/**
 * Autogenerated input type of UpdateTournamentMutation
 */
export interface UpdateTournamentMutationInput {
  clientMutationId?: string | null;
  endAt: any;
  id: string;
  location?: string | null;
  name: string;
  startAt: any;
}

//==============================================================
// END Enums and Input Objects
//==============================================================
